# Generated by Django 3.1 on 2020-08-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('par_cat_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('par_reg_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('performance_date', models.DateTimeField()),
                ('location', models.TextField()),
                ('as_type', models.CharField(choices=[('IN', 'На повышение'), ('DE', 'На понижение')], max_length=30)),
                ('image', models.ImageField(upload_to='img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.region')),
            ],
            options={
                'verbose_name_plural': 'Активы',
            },
        ),
    ]
