# Generated by Django 3.1 on 2020-08-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200828_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='as_type',
            field=models.CharField(choices=[('IN', 'На повышение'), ('DE', 'На понижение')], max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='discription',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.TextField(verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='min_price',
            field=models.IntegerField(verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='performance_date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='par_reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.region', verbose_name='ID родительского региона'),
        ),
    ]
