# Generated by Django 3.1 on 2020-08-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200828_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'актив', 'verbose_name_plural': 'Активы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
