# Generated by Django 3.1 on 2020-08-30 16:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200828_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='description',
        ),
        migrations.AddField(
            model_name='purchase',
            name='discription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='discription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
