# Generated by Django 3.1 on 2020-08-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200830_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'закупка', 'verbose_name_plural': 'Закупки'},
        ),
    ]
