# Generated by Django 3.1 on 2020-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=250, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
    ]
