# Generated by Django 3.1 on 2020-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200831_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bargaining_link',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ссылка на торги'),
        ),
        migrations.AddField(
            model_name='asset',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
