# Generated by Django 3.1 on 2020-08-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200831_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='discription',
            new_name='description',
        ),
    ]
