# Generated by Django 3.1 on 2020-08-30 20:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200831_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='as_type_en',
            field=models.CharField(choices=[('IN', 'На повышение'), ('DE', 'На понижение')], max_length=30, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='asset',
            name='as_type_kz',
            field=models.CharField(choices=[('IN', 'На повышение'), ('DE', 'На понижение')], max_length=30, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='asset',
            name='as_type_ru',
            field=models.CharField(choices=[('IN', 'На повышение'), ('DE', 'На понижение')], max_length=30, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bargaining_link_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на торги'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bargaining_link_kz',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на торги'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bargaining_link_ru',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на торги'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_en',
            field=models.TextField(null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_kz',
            field=models.TextField(null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_ru',
            field=models.TextField(null=True, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='asset',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='asset',
            name='title_kz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='asset',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kz',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='leader',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='leader',
            name='description_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='leader',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='leader',
            name='full_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='leader',
            name='full_name_kz',
            field=models.CharField(max_length=250, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='leader',
            name='full_name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_kz',
            field=models.CharField(max_length=250, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description_kz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='title_kz',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_kz',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
    ]
