# Generated by Django 3.1 on 2020-08-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200831_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='as_type_kz',
            new_name='as_type_kk',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='bargaining_link_kz',
            new_name='bargaining_link_kk',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='location_kz',
            new_name='location_kk',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='full_name_kz',
            new_name='full_name_kk',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='position_kz',
            new_name='position_kk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.AlterField(
            model_name='category',
            name='par_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='region',
            name='par_reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.region', verbose_name='Родительский регион'),
        ),
    ]
