# Generated by Django 3.1 on 2020-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200831_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='file_description',
            field=models.FileField(default='', upload_to='file/', verbose_name='Pdf файл описания'),
            preserve_default=False,
        ),
    ]
