# Generated by Django 3.1 on 2020-08-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_purchase_file_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='file_fiz',
            field=models.FileField(default=None, upload_to='file/', verbose_name='Форма заявки для физ. лиц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='file_kwal',
            field=models.FileField(default='', upload_to='file/', verbose_name='Форма сведений о квалификации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='file_ur',
            field=models.FileField(default='', upload_to='file/', verbose_name='Форма заявки для юр. лиц'),
            preserve_default=False,
        ),
    ]
