# Generated by Django 3.1 on 2020-08-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальная цена'),
        ),
    ]
