# Generated by Django 3.1 on 2020-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20200901_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
