# Generated by Django 3.1 on 2020-09-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200901_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Фото'),
        ),
    ]
