# Generated by Django 3.1 on 2020-09-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200901_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Дата создания'),
        ),
    ]
