# Generated by Django 3.1 on 2020-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20200901_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
