# Generated by Django 3.1 on 2020-09-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20200901_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
