# Generated by Django 3.1 on 2020-09-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'итог', 'verbose_name_plural': 'Итоги'},
        ),
    ]
