# Generated by Django 3.1 on 2020-09-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_audit_finotchet'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Фоновая картинка'),
        ),
        migrations.AddField(
            model_name='audit',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='finotchet',
            name='image',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Фоновая картинка'),
        ),
        migrations.AddField(
            model_name='finotchet',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
