# Generated by Django 3.1 on 2020-09-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20200904_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finotchet',
            options={'verbose_name': 'годовой отчёт', 'verbose_name_plural': 'годовые отчёты'},
        ),
        migrations.AddField(
            model_name='finotchet',
            name='file2',
            field=models.FileField(default='', upload_to='file/', verbose_name='Консолидированная финансовая отчётность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finotchet',
            name='file',
            field=models.FileField(upload_to='file/', verbose_name='Финансовая отчётность'),
        ),
    ]
