# Generated by Django 3.1 on 2020-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20200904_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'verbose_name': 'внешний аудит', 'verbose_name_plural': 'Внешний аудиты'},
        ),
        migrations.AlterField(
            model_name='audit',
            name='file2',
            field=models.FileField(null=True, upload_to='file/', verbose_name='Консолидированная финансовая отчётность'),
        ),
    ]
