# Generated by Django 3.1 on 2020-09-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_asset_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('tags', models.CharField(max_length=250, verbose_name='Теги (через запятую)')),
                ('file', models.FileField(upload_to='file/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.AlterField(
            model_name='finotchet',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.document', verbose_name='Документ'),
        ),
    ]
