# Generated by Django 3.1 on 2020-09-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_audit_filee'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='filee_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doc_2', to='web.document', verbose_name='Документ'),
        ),
    ]
