# Generated by Django 3.1 on 2020-09-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_audit_filee_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='file',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='file2',
        ),
    ]
