# Generated by Django 3.1 on 2020-09-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20200918_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='filee',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='filee_2',
            new_name='file2',
        ),
    ]
