# Generated by Django 3.1 on 2020-09-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_auto_20200918_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='file2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_2', to='web.document', verbose_name='Документ'),
        ),
    ]
