# Generated by Django 3.1 on 2020-09-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_auto_20200918_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='file_description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ff', to='web.document', verbose_name='Pdf файл описания'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='file_fiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aas', to='web.document', verbose_name='Форма заявки для физ. лиц'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='file_kwal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bs', to='web.document', verbose_name='Форма сведений о квалификации'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='file_ur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='qwf', to='web.document', verbose_name='Форма заявки для юр. лиц'),
        ),
    ]
