# Generated by Django 3.1 on 2020-09-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_auto_20200918_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
