# Generated by Django 3.1 on 2020-09-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20200918_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='visits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
