# Generated by Django 3.1 on 2020-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_auto_20200918_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('tags', models.CharField(max_length=250, verbose_name='Теги')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.CharField(max_length=250, verbose_name='Теги'),
        ),
    ]
