# Generated by Django 3.1 on 2020-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_auto_20200920_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.TextField(verbose_name='Теги'),
        ),
    ]
