# Generated by Django 3.1 on 2020-10-08 14:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_auto_20200920_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='img/', verbose_name='Фото')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('position_kk', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'директор',
                'verbose_name_plural': 'директоры',
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='img/', verbose_name='Фото')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('position_kk', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=200, null=True, verbose_name='Должность')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_kk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'член правления',
                'verbose_name_plural': 'члены правления',
            },
        ),
    ]
